Lint test

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -2,11 +2,9 @@ name: Flake8 Linting Check
 
 on:
   push:
-    branches:
-      - main
+    branches: [main]
   pull_request:
-    branches:
-      - main
+    branches: [main]
 
 jobs:
   lint:
@@ -22,11 +20,14 @@ jobs:
         with:
           python-version: '3.9.13'
 
-      - name: Install flake8
+      - name: Install flake8 with extras
         run: |
           python -m pip install --upgrade pip
-          pip install flake8 flake8-pyproject
+          pip install flake8 flake8-pyproject flake8-colors
 
-      - name: Run flake8 linter
+      - name: Run flake8 with pretty output
         run: |
-          flake8 .
+          flake8 . --format=default || {
+            echo "::error file=flake8::Linting errors found. Please fix the issues listed above.";
+            exit 1;
+          }
